### PR TITLE
Update gtest to 1.10.0 version

### PR DESCRIPTION
**Pull request by j-rivero**
Following https://github.com/ros/urdfdom/pull/158#pullrequestreview-760241904 

Two commits on top of pull #158:
  * 3e10ed7 to update gtest code
  * b7c5c23 to fix some warnings related to ` comparison of integer expressions of different signedness`
  * aece008 clang needed c++11 to compile gtest properly

### CODE REVIEW

**Comment by j-rivero** [comment]
ROS2 CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15272/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9988/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12955/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15465/)

**Comment by j-rivero** [comment]
Another try:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15273/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9989/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12956/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15466/)

**Comment by j-rivero** [comment]
Branch was not updated. Rebased:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15277/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9991/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12958/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15469/)

**Review by clalancette — APPROVED** [review]
CI looks good to me, so approving.  What I'll suggest to get this in is:

1. Merge #158
2. Rebase this one on top of master
3. Merge this one
4. Update https://github.com/ros2/ros2/blob/master/ros2.repos to point to the master branch here.
5. Tag this repository and do a source release.  I'll suggest bumping the major version to 3.0.
6. Do a release of this package into Rolling.

**Comment by clalancette** [comment]
All right, I've approved, CI is green, and I verified that the changes before and after the rebase are 100% the same.  So this is good to go, I'm going to go ahead and merge.  Thanks @j-rivero .

**Pull request merged**
