### PR TITLE
Remove gtest from the sources.

### PR DESCRIPTION
**Pull request by clalancette**
It is only used very sparingly, and gets rid of a vendored
package that causes warnings.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

@scpeters @sloretz I'd appreciate review of this, as it will get rid of one of the long-standing warnings in ROS 2 CI: https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/750/clang/new/ .

Note that the other way we could go here is to update gtest to a newer version, but this seemed simpler to me.

### CODE REVIEW

**Review by sloretz — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14288/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9077/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11972/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14390/)
* Linux Clang [Build Status](http://ci.ros2.org/job/ci_linux_clang_libcxx/2/)

**Review by scpeters — APPROVED** [review]

**Comment by scpeters** [comment]
feel free to merge

**Comment by Karsten1987** [comment]
@clalancette can you please backport this to Foxy? Or at least the part indicated in #151

**Comment by clalancette** [comment]
See #155

**Pull request merged**
