### PR TITLE
add add_material() function in Robot class

### PR DESCRIPTION
**Pull request by keulYSMB**
defined a new method add_material and modified add_aggregate to allow material aggregation

This allow to have global materials and just call them using their name inside visual tags

### CODE REVIEW

**Comment by jacquelinekay** [comment]
hey hey,

I implemented a very simple test for add_material in branch `material_test` that reads the material from a link and adds it to the robot as an aggregate material:

https://github.com/ros/urdfdom/tree/material_test

@keulYSMB and @eacousineau, take a look. If it looks good to everyone, we should merge this.

**Comment by keulYSMB** [comment]
Looks good to me,

Thanks Jackie, I completely forgot to create this test.

+1

**Comment by jacquelinekay** [comment]
Can you merge that branch with your fork and then I'll merge this PR?

**Comment by eacousineau** [comment]
Code looks good!

One question on design, though: Can I ask why you added the urdf.Material object to the top-lvel urdf.Robot's item registry?
I notice you're doing that, but in the rendered XML file, it is contained in the <link> tag's body, and not necessarily in the robot's XML. (My intent was that the Robot's aggregate types be its direct children whose order may be important for functional / aesthetic purposes - granted, this intent was undocumented haha).

**Comment by keulYSMB** [comment]
@eacousineau That is a very good remark Eric.
I think that I just followed the structure used for link and joint. I actually don't remember what was the motivation for aggregating materials as part of the Robot XML. I think I added a map for my convenience because I wanted to declare the materials once and use them in numerous of visual/collision tags by referring them by name.
How would you like to implement materials ? just fill the material list in the Robot class ?

**Comment by scpeters** [comment]
ping @eacousineau: did you see the last question by @keulYSMB ?

**Comment by jacquelinekay** [comment]
I'd like to make a decision on this PR soon because the urdf_parser_py folder will soon be in its own repository, and I don't think pull requests will be preserved when I move it.

However I'm not really sure how to answer Mikael's question, since the original design for the aggregate feature isn't documented and it's not in the spec...

**Comment by keulYSMB** [comment]
IMO you can discard it, its not much of an improvement and I don't have
knowledge of any project relying on it. So I assume that if someone
actually needs the feature a new PR will be made.

**Comment by jacquelinekay** [comment]
Sounds good to me.

**Pull request closed without merging**
