### PR TITLE
Merge the master branch onto the ros2 branch

### PR DESCRIPTION
**Pull request by clalancette**
This merge is meant to get the latest fixes from the master branch onto the ros2 branch.  In particular, the changes that are most interesting here are:

1.  Changes to fix URDF parsing when different locales are used.
1.  Addition of the the "version" attribute to URDF.
1.  Addition of some tests.

There are also a bunch of other minor fixes and such in here.

This is meant to be merged as a merge commit; that's so that we don't change any of the commits that we are merging in.

### CODE REVIEW

**Comment by clalancette** [comment]
ROS 2 CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12884/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7839/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10601/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12827/)

**Comment by clalancette** [comment]
Now that we landed #148, I've re-merged this with that commit in place.  I'll run another CI on ros2 infrastructure for now.  Once we have this in, I'll go back to trying to make this work for both ROS 1, ROS 2, and external builders.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12968/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7918/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10689/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12918/)

**Comment by scpeters** [comment]
> * Windows [Build Status](http://ci.ros2.org/job/ci_windows/12918/)

windows build failed with an unrelated Qt installation issue

**Comment by clalancette** [comment]
> windows build failed with an unrelated Qt installation issue

Yeah, that's an ongoing issue with CI right now.  It's being worked on.

But I do think we should hold off on this until we get a green CI for Windows.  If anything is going to break, it is going to be Windows ;).

**Comment by sloretz** [comment]
Does this repo need a `ros2` branch? It looks like it's a plain CMake package. How about going the other direction - merging `ros2` into `master` and using that from now on.

**Comment by clalancette** [comment]
> Does this repo need a `ros2` branch? It looks like it's a plain CMake package. How about going the other direction - merging `ros2` into `master` and using that from now on.

That is the eventual plan.  In order to get there, I need to basically do what I said in https://github.com/ros/urdfdom/pull/148#issuecomment-720465597, which is to make the vendor packages optional, restore travis, and also deal with the package.xml (since it exists on the `ros2` branch, but not on the `master` branch).

That was enough work that I felt like it was better to synchronize them this way (to get these changes into ROS 2), and then work on bringing the `ros2` branch back into `master`.

**Comment by clalancette** [comment]
Superseded by #158, where we merge the two branches together onto the master branch.

**Pull request closed without merging**
